#include "stdafx.h"

#ifndef _COUNTRY_CODES_DEF

#define _COUNTRY_CODES_DEF

struct _COUNTRYCODES
{ 
	char szCountryCode[3];	
	char szCountryName[40];
};

_COUNTRYCODES CountryCodes[] = 
{
"AF","Afghanistan",
"AL","Albania",
"DZ","Algeria",
"AS","American Samoa",
"AD","Andorra",
"AO","Angola",
"AI","Anguilla",
"AQ","Antarctica",
"AG","Antigua and Barbuda",
"AR","Argentina",
"AM","Armenia",
"AW","Aruba",
"AU","Australia",
"AT","Austria",
"AZ","Azerbaijan",
"BS","Bahamas",
"BH","Bahrain",
"BD","Bangladesh",
"BB","Barbados",
"BY","Belarus",
"BE","Belgium",
"BZ","Belize",
"BJ","Benin",
"BM","Bermuda",
"BT","Bhutan",
"BO","Bolivia",
"BA","Bosnia and Herzegovina",
"BW","Botswana",
"BV","Bouvet Island",
"BR","Brazil",
"IO","British Indian Ocean Territory",
"BN","Brunei Darussalam",
"BG","Bulgaria",
"BF","Burkina Faso",
"BI","Burundi",
"KH","Cambodia",
"CM","Cameroon",
"CA","Canada",
"CV","Cape Verde",
"KY","Cayman Islands",
"CF","Central African Republic",
"TD","Chad",
"CL","Chile",
"CN","China",
"CO","Colombia",
"KM","Comoros",
"CG","Congo",
"CD","Congo, The Democratic Republic of the",
"CK","Cook Islands",
"CR","Costa Rica",
"CI","Cote D'Ivoire",
"HR","Croatia",
"CU","Cuba",
"CY","Cyprus",
"CZ","Czech Republic",
"DK","Denmark",
"DJ","Djibouti",
"DM","Dominica",
"DO","Dominican Republic",
"EC","Ecuador",
"EG","Egypt",
"SV","El Salvador",
"GQ","Equatorial Guinea",
"ER","Eritrea",
"EE","Estonia",
"ET","Ethiopia",
"EU","Europe",
"FK","Falkland Islands (Malvinas)",
"FO","Faroe Islands",
"FJ","Fiji",
"FI","Finland",
"FR","France",
"GF","French Guiana",
"PF","French Polynesia",
"GA","Gabon",
"GM","Gambia",
"GE","Georgia",
"DE","Germany",
"GH","Ghana",
"GI","Gibraltar",
"GR","Greece",
"GL","Greenland",
"GD","Grenada",
"GP","Guadeloupe",
"GU","Guam",
"GT","Guatemala",
"GN","Guinea",
"GW","Guinea-Bissau",
"GY","Guyana",
"HT","Haiti",
"HM","Heard Island and McDonald Islands",
"VA","Holy See (Vatican City State)",
"HN","Honduras",
"HK","Hong Kong",
"HU","Hungary",
"IS","Iceland",
"IN","India",
"ID","Indonesia",
"IR","Iran, Islamic Republic of",
"IQ","Iraq",
"IE","Ireland",
"IL","Israel",
"IT","Italy",
"JM","Jamaica",
"JP","Japan",
"JO","Jordan",
"KZ","Kazakstan",
"KE","Kenya",
"KI","Kiribati",
"KP","Korea, Democratic People's Republic of",
"KR","Korea, Republic of",
"KW","Kuwait",
"KG","Kyrgyzstan",
"LA","Lao People's Democratic Republic",
"LV","Latvia",
"LB","Lebanon",
"LS","Lesotho",
"LR","Liberia",
"LY","Libyan Arab Jamahiriya",
"LI","Liechtenstein",
"LT","Lithuania",
"LU","Luxembourg",
"MO","Macau",
"MK","Macedonia",
"MG","Madagascar",
"MW","Malawi",
"MY","Malaysia",
"MV","Maldives",
"ML","Mali",
"MT","Malta",
"MH","Marshall Islands",
"MQ","Martinique",
"MR","Mauritania",
"MU","Mauritius",
"YT","Mayotte",
"MX","Mexico",
"FM","Micronesia, Federated States of",
"MD","Moldova, Republic of",
"MC","Monaco",
"MN","Mongolia",
"MS","Montserrat",
"MA","Morocco",
"MZ","Mozambique",
"MM","Myanmar",
"NA","Namibia",
"NR","Nauru",
"NP","Nepal",
"NL","Netherlands",
"AN","Netherlands Antilles",
"NC","New Caledonia",
"NZ","New Zealand",
"NI","Nicaragua",
"NE","Niger",
"NG","Nigeria",
"NU","Niue",
"NF","Norfolk Island",
"MP","Northern Mariana Islands",
"NO","Norway",
"OM","Oman",
"PK","Pakistan",
"PW","Palau",
"PS","Palestinian Territory, Occupied",
"PA","Panama",
"PG","Papua New Guinea",
"PY","Paraguay",
"PE","Peru",
"PH","Philippines",
"PL","Poland",
"PT","Portugal",
"PR","Puerto Rico",
"QA","Qatar",
"RE","Reunion",
"RO","Romania",
"RU","Russian Federation",
"RW","Rwanda",
"KN","Saint Kitts and Nevis",
"LC","Saint Lucia",
"VC","Saint Vincent and the Grenadines",
"WS","Samoa",
"SM","San Marino",
"ST","Sao Tome and Principe",
"SA","Saudi Arabia",
"SN","Senegal",
"RS","Serbia",
"SC","Seychelles",
"SL","Sierra Leone",
"SG","Singapore",
"SK","Slovakia",
"SI","Slovenia",
"SB","Solomon Islands",
"SO","Somalia",
"ZA","South Africa",
"ES","Spain",
"LK","Sri Lanka",
"SD","Sudan",
"SR","Suriname",
"SZ","Swaziland",
"SE","Sweden",
"CH","Switzerland",
"SY","Syrian Arab Republic",
"TW","Taiwan",
"TJ","Tajikistan",
"TZ","Tanzania, United Republic of",
"TH","Thailand",
"TG","Togo",
"TK","Tokelau",
"TO","Tonga",
"TT","Trinidad and Tobago",
"TN","Tunisia",
"TR","Turkey",
"TM","Turkmenistan",
"TC","Turks and Caicos Islands",
"TV","Tuvalu",
"UG","Uganda",
"UA","Ukraine",
"AE","United Arab Emirates",
"GB","United Kingdom",
"US","United States",
"UM","United States Minor Outlying Islands",
"UY","Uruguay",
"UZ","Uzbekistan",
"VU","Vanuatu",
"VE","Venezuela",
"VN","Vietnam",
"VG","Virgin Islands, British",
"VI","Virgin Islands, U.S.",
"WF","Wallis and Futuna",
"YE","Yemen",
"ZM","Zambia",
"ZW","Zimbabwe",
"ZZ","Unknown"
};
/*
_COUNTRYCODES _old_CountryCodes[] = 
{
"ae",
"af",
"al",
"am",
"an",
"ao",
"ar",
"at",
"au",
"aw",
"az",
"ba",
"bb",
"bd",
"be",
"bf",
"bg",
"bh",
"bi",
"bj",
"bm",
"bn",
"bo",
"br",
"bs",
"bt",
"bw",
"by",
"bz",
"ca",
"cf",
"cg",
"ch",
"ci",
"ck",
"cl",
"cm",
"cn",
"co",
"cr",
"cu",
"cv",
"cy",
"cz",
"de",
"dk",
"dz",
"ec",
"ee",
"eg",
"er",
"es",
"et",
"eu",
"fi",
"fj",
"fo",
"fr",
"ga",
"gb",
"gd",
"ge",
"gf",
"gi",
"gl",
"gp",
"gr",
"gt",
"gu",
"gy",
"hk",
"hr",
"ht",
"hu",
"id",
"ie",
"il",
"in",
"iq",
"ir",
"is",
"it",
"jm",
"jo",
"jp",
"ke",
"kg",
"kh",
"ki",
"kp",
"kr",
"ky",
"kz",
"la",
"lb",
"lc",
"le",
"lk",
"lt",
"lu",
"lv",
"ly",
"ma",
"mc",
"md",
"mg",
"mn",
"mo",
"mp",
"mq",
"ms",
"mt",
"mx",
"my",
"mz",
"na",
"nc",
"nf",
"nl",
"no",
"np",
"nr",
"nz",
"om",
"pa",
"pe",
"pf",
"ph",
"pk",
"pl",
"pm",
"pr",
"pt",
"py",
"qa",
"re",
"ro",
"ru",
"rw",
"sa",
"sb",
"sd",
"se",
"sg",
"si",
"sk",
"sl",
"so",
"tc",
"tf",
"tg",
"th",
"tn",
"to",
"tp",
"tr",
"tt",
"tv",
"tw",
"tz",
"ua",
"ug",
"uk",
"us",
"uy",
"va",
"ve",
"vg",
"vi",
"vn",
"ws",
"ye",
"yu",
"za",
"zw",
"zz"};
*/

#endif