//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameScanner.rc
//
#define IDC_MYICON                      2
#define IDD_GAMESCANNER_DIALOG          102
#define IDD_NODISKVIEWER_DIALOG         102
#define IDD_ADD_SERVER                  102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_ADD_TO_FAVORITES            104
#define IDM_EXIT                        105
#define IDS_FAST_CONNECT                105
#define IDS_DOWNLOAD                    106
#define IDD_ADD_NEW_GAME_INSTALLATION   106
#define IDI_GAMESCANNER                 107
#define IDI_NODISKVIEWER                107
#define IDS_REFRESH_FILTER              107
#define IDS_COLOR_FONT                  108
#define IDC_GAMESCANNER                 109
#define IDS_ADD_NEW_BUDDY               110
#define IDR_MAINFRAME                   128
#define IDI_SMALL                       129
#define IDI_ICON1                       130
#define IDI_ICON2                       131
#define IDR_MENU1                       131
#define IDI_ICON                        131
#define IDD_DLG_SETPRIVPASS             131
#define IDI_ICON3                       132
#define IDD_DLG_PROGRESS                133
#define IDR_241                         139
#define IDD_DLG_ADD_BUDDY               140
#define IDI_ICON_PB                     140
#define IDI_ICON_FAVORITES              141
#define IDI_ICON10                      142
#define IDI_ICON_BUDDY                  142
#define IDI_ICON13                      144
#define IDI_ICON_WARNING                144
#define IDI_ICON_ERROR                  146
#define IDI_ICON12                      147
#define IDI_ICON_LOCKED                 147
#define IDD_DLG_RCON                    148
#define IDI_ICON_UNKOWN                 148
#define IDD_DIALOG_RCON_PASS            149
#define IDD_DLG_RCON_PASS               149
#define ICON_INFO                       190
#define IDI_ICON14                      195
#define IDI_ICON_REFRESH                195
#define IDI_ICON_SEARCH                 198
#define IDI_ICON_OPTIONS                199
#define IDI_ICON11                      200
#define IDI_ICON_STOP                   200
#define IDD_DIALOG_CONFIG               201
#define IDD_CFG1                        202
#define IDD_CFG2                        203
#define IDI_ICON_SLIDER                 204
#define IDD_CFG4                        205
#define IDD_CFG5                        206
#define IDD_DLG_MAXMIN_PLY              207
#define ID_DLG_ENUMERATE_GAMES          207
#define IDD_CFG3_ET2                    208
#define IDD_CFG6                        208
#define IDD_CFG_NET                     208
#define IDI_ICON_SLIDER1                212
#define IDI_ICON_FAVORITE_ADD           213
#define IDI_ICON_LAN                    229
#define IDI_ICON_GLOBE                  231
#define IDI_ICON_FILTER                 233
#define IDI_ICON_CHECKBOX               235
#define IDI_ICON_CHECKEDBOX             236
#define IDI_ICON_HISTORY                238
#define IDI_ICON_TRICHECKEDBOX          239
#define IDB_BITMAP_LOCK                 241
#define IDB_BITMAP4                     247
#define IDB_BITMAP_CONNECT              249
#define IDB_BITMAP_REFRESH_SMALL        251
#define IDB_BITMAP_STOP_SMALL           252
#define IDB_BITMAP_SETTINGS_DISABLED1   254
#define IDI_ICON_FOLDER                 256
#define IDI_ICON_RANKED                 261
#define IDI_ICON_BLANK                  262
#define IDI_ICON5                       267
#define IDC_ETSERVERVIEWER              270
#define IDI_ICON_SETTINGS               271
#define IDI_ICON_FILTER2                272
#define IDB_TOOLBAR_N                   276
#define IDB_TOOLBAR_D                   281
#define IDB_TOOLBAR_H                   282
#define IDB_DOWNARROW                   283
#define IDB_BITMAP2                     284
#define IDB_UPARROW                     284
#define IDI_ICON_VAC                    286
#define IDI_ICON6                       287
#define IDI_ICON_RCON                   288
#define IDC_LIST_PLAYERS                1000
#define IDC_CHECK_COLFILTER             1000
#define IDC_MAP_PREVIEW                 1001
#define ID_RCON_CONNECT                 1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON_DEFAULT              1002
#define IDC_BUTTON_BUDDY_SCAN           1002
#define IDC_BUTTON_APPLY                1002
#define IDC_STATIC_RCON_INFO            1002
#define IDC_BUTTON_SEL_FONT             1002
#define IDC_BUTTON_CFG_EXE_CANCEL       1002
#define IDC_BUTTON2                     1003
#define IDC_BUTTON_SRV2                 1003
#define IDC_SLIDER_TRANS                1003
#define IDC_BUTTON_ADD_SERVER           1003
#define IDC_EDIT_MIRC                   1003
#define IDC_BUTTON_EXE_CFG_OK           1003
#define IDC_BUTTON_JOIN                 1004
#define IDC_EDIT_PASS                   1004
#define IDC_BUTTON_SRV3                 1005
#define IDC_STATIC_TEXT                 1005
#define IDC_LIST_CFG_EXES               1005
#define IDC_BUTTON_SRV4                 1006
#define IDC_EDIT_MASTER_SERVER          1006
#define IDC_EDIT_CFG_VERSION            1006
#define IDC_LIST2                       1007
#define IDC_EDIT_MASTER_PORT            1007
#define IDC_EDIT_CFG_MOD                1007
#define IDC_CHECK1                      1008
#define IDC_EDIT_CFG_VERSION2           1008
#define IDC_BUTTON3                     1008
#define IDC_EDIT_CFG_PROPNAME           1008
#define IDC_CHECK2                      1009
#define IDC_CHECK3                      1010
#define IDC_CHECK5                      1011
#define IDC_BUTTON_CANCEL               1012
#define IDC_BUTTON4                     1013
#define IDC_EDIT_PROTOCOL               1013
#define IDC_BUTTON_FIND                 1013
#define IDC_EDIT_PATH                   1014
#define IDC_BUTTON_ET_PATH              1015
#define IDC_CHECK_ENABLE_NOTIFY         1016
#define IDC_COMBO_MOD                   1017
#define IDC_COMBO1                      1017
#define IDC_COMBO_PING                  1017
#define IDC_COMBO_GAMES                 1017
#define IDC_EDIT_KEY                    1018
#define IDC_CHECK_FILTER_FAVORITES      1019
#define IDC_EDIT_SOCK_TIMEOUT_S         1020
#define IDC_EDIT_SOCK_TIMEOUT_MS        1021
#define IDC_EDIT_EXT_EXE                1022
#define IDC_CUSTOM1                     1022
#define IDC_EDIT_EXT_CMD                1023
#define IDC_STATIC_PANE_V               1023
#define IDC_EXT_EXE                     1024
#define IDC_STATIC_CS                   1024
#define IDC_EDIT_CS_PASSWORD            1025
#define IDC_LIST_SERVER                 1026
#define IDC_EDIT_IP                     1027
#define IDC_LIST_BUDDY                  1027
#define IDC_EDIT_PORT                   1028
#define IDC_STATIC_PASSWORD             1028
#define IDC_BUTTON_OK                   1029
#define IDC_STATIC_RCON_PASSWORD        1029
#define IDC_STATIC_CS_SERVERNAME        1030
#define IDC_BUTTON_REFRESH              1031
#define IDC_STATIC_CS_COUNTRY           1032
#define IDC_STATIC_RSS_FEEDER           1034
#define IDC_STATIC_RSS_TITLE            1035
#define IDC_COMBOBOXEX_CMD              1036
#define IDC_BUTTON_QUICK_CONNECT        1037
#define IDC_EDIT_QUICK_PASSWORD         1038
#define IDC_CHECK_EXT_MIN               1039
#define IDC_CHECK_EXT_CLOSE             1040
#define IDC_CHECK_FAVORITES             1040
#define IDC_EDIT_EXT_WINDOWNAME         1042
#define IDC_BUTTON_CFG_MASTER_SRV       1043
#define IDC_LIST_CONFIG                 1043
#define IDC_CHECK_EXACT_MATCH           1044
#define IDC_STATIC_INSTALL_PATH         1045
#define IDC_CHECK_NO_COLOR_MATCH        1045
#define IDC_CHECK_LOG                   1046
#define IDC_TREE_CONF                   1046
#define IDC_EDIT_WINDOWNAME             1047
#define IDC_MAIN_TREE                   1047
#define IDC_CHECK_EXT_ACTIVE            1048
#define IDC_CHECK_SCR_RESTORE           1049
#define IDC_EDIT_NICKNAME_FILTER        1050
#define IDC_STATIC_GAME_NAME            1050
#define IDC_EDIT_NICKNAME_COLOR         1051
#define IDC_CUSTOM_UPDATE               1051
#define IDC_CUSTOM2                     1052
#define IDC_TAB2                        1053
#define IDC_CHECK_ACTIVE                1053
#define IDC_EDIT_STATUS                 1054
#define IDC_BUTTON_APPLY_GENERAL        1054
#define IDC_PROGRESS1                   1055
#define IDC_BUTTON_APPLY_MINIMIZER      1055
#define IDC_STATIC_FILTER               1056
#define IDC_BUTTON_APPLY_EXT            1056
#define IDC_CHECK_EMPTY                 1057
#define IDC_BUTTON_APPLY_LOOK           1057
#define IDC_CHECK_FULL                  1058
#define IDC_CHECK_ETPRO                 1059
#define IDC_CHECK_MIRC                  1059
#define IDC_CHECK_PRIVATE               1060
#define IDC_EDIT_MINMAX                 1060
#define IDC_CHECK6                      1061
#define IDC_CHECK_PB                    1061
#define IDC_SLIDER_THREADS              1061
#define IDC_HOTKEY1                     1062
#define IDC_BUTTON5                     1063
#define IDC_BUTTON_RESCAN               1063
#define IDC_COMBO_COUNTRY               1064
#define IDC_BUTTON_GETMASTER_LIST       1065
#define IDC_EDIT_CMD                    1066
#define IDC_LIST_RCON                   1068
#define IDC_EDIT_PASSWORD               1069
#define IDC_EDIT_CS_RCON_PASSWORD       1070
#define IDC_BUTTON_PANE_V               1071
#define IDC_DOWNLOAD                    1072
#define IDC_CHECK_SHORTNAME             1073
#define IDC_MAINTREE                    1074
#define IDI_ICON_USERS                  1075
#define IDD_DIALOG_STATS                1077
#define IDD_CFG3_NEW                    1078
#define IDD_CFG_MIRC                    1079
#define IDD_DLG_MINMAX_PLY              1080
#define IDI_ICON_STATS                  1082
#define IDI_ICON_PAINT                  1083
#define IDI_ICON_LOGGER                 1084
#define IDI_ICON_FONT                   1086
#define IDI_ICON7                       1090
#define IDI_ICON_RULES                  1090
#define IDI_ICON_APP_LOGO1              1091
#define IDI_ICONQUAKE2                  1093
#define IDI_ICON_TASKTRAY               1098
#define IDC_BUTTON_ADD_INSTALL          1101
#define IDI_ICON9                       1101
#define IDC_BUTTON_EDIT_INSTALL         1102
#define IDC_BUTTON_DELETE_INSTALL       1103
#define IDC_EDIT_CFG_RETRIES            1104
#define IDC_CHECK_USE_HTTP              1105
#define IDC_COMBO_LANG                  1106
#define IDI_ICON_MIRC                   1107
#define IDI_ICON4                       1109
#define IDI_ICON_NEW_GS_LOGO            1109
#define IDC_STATIC_BUDDY_NAME           1200
#define IDC_TAB1                        1201
#define IDC_STATIC_EXE                  1202
#define IDC_STATIC_COMMAND              1203
#define IDC_STATIC_ADDNEWINSTALL        1204
#define IDC_STATIC_VERSION              1205
#define IDC_STATIC_MOD                  1206
#define IDC_SLIDER_SLEEP_VAL            1207
#define IDC_STATIC_SLEEP_VAL            1208
#define IDC_STATIC_ABC123               1209
#define IDC_CHECK_CONNECT_CLOSE         1210
#define IDC_STATIC_EDIT_LABEL           1211
#define IDC_STATIC_WEB_PROTOCOL         1212
#define IDC_CHECK_REG_WEB_PROTOCOLS     1213
#define IDC_STATIC_LABEL                1214
#define IDM_OPEN                        32771
#define ID_BUDDY_ADDFROMPLAYERLIST32771 32771
#define IDM_HOMEPAGE                    32772
#define ID_BUDDY_ADDNEW                 32772
#define IDM_SETTINGS                    32773
#define ID_TT_SERVER1                   32774
#define IDM_ADD                         32775
#define ID_FOO2_SERVER3                 32776
#define ID_BUDDY_REMOVESELECTEDBUDDY    32776
#define ID_FOO2_SERVER4                 32777
#define ID_FILE_EXPORT                  32777
#define IDM_DELETE                      32778
#define ID_EXPORT_ALL                   32778
#define IDM_CONNECT                     32779
#define ID_EXPORT_FAVORITES             32779
#define ID_FILE_OPEN                    32780
#define ID_TT_SERVER3                   32780
#define ID_EXPORT_ALL_SERVERS           32780
#define ID_OPTIONS_BROWSESERVERS        32781
#define ID_TT_SERVER4                   32781
#define ID_FILE_IMPORT                  32781
#define ID_HELP_GOTOSPLATTERLADDER      32782
#define ID_IMPORT_SERVERS               32782
#define ID_FILE_LOADSERVERLIST          32783
#define ID_FILE_SAVESERVERLIST          32784
#define IDM_PRIVPASS                    32784
#define ID_OPTIONS_REFRESH              32785
#define ID_FOO_FORCECONNECTDEFET        32785
#define ID_HELP_GOTOGAMESTV             32786
#define IDM_FORCE_CONNECT               32786
#define ID_HELP_GOTOET                  32787
#define ID_HELP_QUICKLINKS              32788
#define ID_VIEW_BUDDYLIST               32789
#define ID_VIEW_MAPPREVIEW              32790
#define ID_VIEW_SERVERRULES             32791
#define IDM_UPDATE                      32792
#define ID_VIEW_PLAYERLIST              32793
#define ID_FILE_DELETEALLFAVORITES      32794
#define ID_FOO_ADDIP                    32795
#define ID_CTRL_V                       32795
#define ID_FOO_COPYIPTOCLIPBOARD        32796
#define IDM_COPYIPTOCLIPBOARD           32797
#define IDM_ADDIP                       32798
#define IDM_COPYIP                      32799
#define ID_HELP_DOCUMENTATIONFAQ        32799
#define ID_BUDDY_ADD                    32800
#define ID_FOO_MINIMUMPLAYERS           32800
#define ID_BUDDY_REMOVE                 32801
#define ID_FOO_MAXIMUMPLAYERS           32801
#define ID_SERVERLIST_PURGEPUBLICSERVLIST 32802
#define ID_SERVERLIST_REFRESHSERVERLIST 32803
#define ID_HELP_GOTOSWERTCW             32804
#define ID_HELP_GOTOXFIRE               32805
#define ID_FAVORITES_ADDIP              32806
#define ID_BUDDY_ADDFROMPLAYERLIST      32807
#define ID_FAVORITES_REMOVE             32808
#define ID_OPTIONS_RCON                 32809
#define ID_TT_SERVER2                   32879
#define ID_YAWN_SERVER                  32880
#define ID_YAWN_PLAYER                  32881
#define ID_KICK_PLAYER                  32882
#define ID_WARN_PLAYER                  32883
#define ID_MUTE_PLAYER                  32884
#define ID_UNMUTE_PLAYER                32885
#define IDM_EDIT_BUDDY                  32886
#define IDC_BUTTON_OPTIONS              32887
#define IDM_REFRESH                     32888
#define IDS_OPTIONS                     32889
#define IDS_REFRESH                     32890
#define IDS_SEARCH                      32891
#define IDM_SCAN                        32892
#define IDM_SCAN_FILTERED               32894
#define IDM_SCAN_ALL_GAMES              32895
#define IDM_LAUNCH_GAME_ONLY            32896
#define IDC_STATIC_THREAD               32897
#define ID_STATS_PLAYER                 32898
#define IDC_EDIT_LOGGER                 32899
#define IDM_RESTORE_COLUMNS             32900
#define IDM_DELETE_SERVERLIST           32901
#define IDM_FONT_COLOR                  32902
#define IDM_COPY_VERSION                32903
#define IDM_COPY_MODNAME                32904
#define IDM_EDIT_RULE                   32905
#define IDM_COPY_RULE                   32906
#define IDC_STATIC                      -1
#define ID_THREAD                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        1110
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1215
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
